spring.application.name=FauxFinderAi

server.port=${PORT:5000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fauxfinder?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

ml.python.executable=${PYTHON_EXEC:C:/Users/rampa/AppData/Local/Programs/Python/Python310/python.exe}
ml.script.path=${ML_SCRIPT_PATH:C:/Users/rampa/OneDrive/Desktop/FauxFinder AI/ml/predict.py}
